[linux_servers]
linux01 ansible_host=192.168.56.21
linux02 ansible_host=192.168.56.22

[linux_servers:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=/home/vagrant/.ssh/ansible_lab
ansible_python_interpreter=/usr/bin/python3
